name: Keep Render Service Alive

on:
  schedule:
    # Runs every 10 minutes (adjust as needed)
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  ping-service:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping Render Service
      run: |
        echo "Pinging service to keep it alive..."
        curl -f https://otp-backend-lr0y.onrender.com/ || echo "Service might be sleeping, continuing..."
        echo "Ping completed at $(date)"
